### ISSUE TITLE
Bounding Boxes are off

### ISSUE THREAD

**Issue by bigbaliboy** [vladiH/flutter_vision#14]
Followed readme and the example provided. The resulting bounding boxes are out of place for my custom trained yolov5 model (and yolov8 model). Also the confidence scores are always very high. 
` List<Widget> displayBoxesAroundRecognizedObjects(Size screen) {
    if (yoloResults.isEmpty) return [];

    double factorX = screen.width / (cameraImage?.height ?? 1);
    double factorY = screen.height / (cameraImage?.width ?? 1);

    // print("screen width"+ screen.width.toString());
    // print("screen height"+ screen.height.toString());
    // print("camera image width");
    // print(cameraImage?.width);
    // print("camera image height");
    // print(cameraImage?.height);
    //
    // print("factor X"+ factorX.toString());
    // print("factor Y"+ factorY.toString());

    Color colorPick = const Color.fromARGB(255, 50, 233, 30);

    return yoloResults.map((result) {
      return Positioned(
        left: result["box"][0] * factorX,
        top: result["box"][1] * factorY,
        right: result["box"][2] * factorX,
        bottom: result["box"][3] * factorY,
        child: Container(
          decoration: BoxDecoration(
            borderRadius: const BorderRadius.all(Radius.circular(10.0)),
            border: Border.all(color: Colors.pink, width: 2.0),
          ),
          child: Text(
            "${result['tag']} ${(result['box'][4] * 100).toStringAsFixed(0)}%",
            style: TextStyle(
              background: Paint()..color = colorPick,
              color: Colors.white,
              fontSize: 18.0,
            ),
          ),
        ),
      );
    }).toList();
  }
`

**Comment by vladiH** [comment]
New version released
