### ISSUE TITLE
Costome yolo model not work

### ISSUE THREAD

**Issue by arupnaskarbkp** [vladiH/flutter_vision#15]
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(100, Error on load Yolov5 model, java.lang.IllegalArgumentException: Internal error: Cannot create interpreter: Following operations are not supported by GPU delegate:
E/flutter (12733): DELEGATE TfLiteFlexDelegate: Operation is not supported.
E/flutter (12733): DEQUANTIZE: 
E/flutter (12733): 35 operations will run on the GPU, and the remaining 340 operations will run on the CPU.
E/flutter (12733): Can not open OpenCL library on this device - dlopen failed: library "libOpenCL.so" not found
E/flutter (12733): Falling back to OpenGL
E/flutter (12733): TfLiteGpuDelegate Init: No shader implementation for transpose
E/flutter (12733): TfLiteGpuDelegate Prepare: delegate is not initialized

**Comment by vladiH** [comment]
I think this error happened because you used the GPU option, but your device does not have a GPU. Please run the program again with the GPU option set to false and come back to share your results. Thank you.
