### ISSUE TITLE
Model does not make any inference in new update

### ISSUE THREAD

**Issue by bigbaliboy** [vladiH/flutter_vision#17]
The model which works perfectly with flutter SDK 3.7.7, does not work with 3.7.9 and with android 11.

**Comment by vladiH** [comment]
Have you perhaps received some warning messages? Or could you please share your settings for testing in a new environment?

**Comment by bigbaliboy** [comment]
Here's some of the messages. 
`I/CameraManagerGlobal(19454): Connecting to camera service
W/CameraManagerGlobal(19454): [soar.cts] ignore the status update of camera: 2
W/CameraManagerGlobal(19454): [soar.cts] ignore the status update of camera: 3
W/CameraManagerGlobal(19454): [soar.cts] ignore the status update of camera: 4
W/CameraManagerGlobal(19454): [soar.cts] ignore the status update of camera: 5
W/CameraManagerGlobal(19454): ignore the torch status update of camera: 3
W/CameraManagerGlobal(19454): ignore the torch status update of camera: 4
I/CameraMetadataJV(19454): setAppNameAndSensorId all [com.antutu:0,ssize,8160x6144,0,false]
I/CameraMetadataJV(19454): setAppNameAndSensorId all [com.antutu:1,ssize,2592x1944,0,false]
E/LB      (19454): fail to open file: No such file or directory
I/xample.new_pro(19454): ProcessProfilingInfo new_methods=1074 is saved saved_to_disk=1 resolve_classes_delay=8000
D/FrameIndicator(19454): support status: 1 0x750059b018 0x750059b4c4
W/Camera  (19454): The selected imageFormatGroup is not supported by Android. Defaulting to yuv420
D/FrameIndicator(19454): support status: 1 0x750059b018 0x750059b4c4
D/CameraInjector(19454): notifyRF for API 2 : cameraRoleId = 0, active = true
D/CameraInjector(19454): notifyRF cameraId = 0, active ? true
E/MiuiCameraCoveredManagerImpl(19454): check service failed
E/MiuiCameraCoveredManager(19454): SetCoveredPackageName error, the MiuiCameraCoveredManagerService not ready!
E/CameraManagerGlobal(19454): Camera 3 is not available. Ignore physical camera status change
W/CameraManagerGlobal(19454): ignore the torch status update of camera: 3
W/CameraManagerGlobal(19454): ignore the torch status update of camera: 4
I/Camera  (19454): startPreview
D/FrameIndicator(19454): support status: 1 0x750059b018 0x750059b4c4
W/BpBinder(19454): Slow Binder: BpBinder transact took 250 ms, interface=android.hardware.camera2.ICameraDeviceUser, code=6 oneway=false
I/Camera  (19454): CameraCaptureSession onConfigured
I/Camera  (19454): Updating builder settings
D/Camera  (19454): Updating builder with feature: ExposureLockFeature
D/Camera  (19454): Updating builder with feature: ExposurePointFeature
D/Camera  (19454): Updating builder with feature: ZoomLevelFeature
D/Camera  (19454): Updating builder with feature: AutoFocusFeature
D/Camera  (19454): Updating builder with feature: NoiseReductionFeature
I/Camera  (19454): updateNoiseReduction | currentSetting: fast
D/Camera  (19454): Updating builder with feature: FocusPointFeature
D/Camera  (19454): Updating builder with feature: ResolutionFeature
D/Camera  (19454): Updating builder with feature: SensorOrientationFeature
D/Camera  (19454): Updating builder with feature: FlashFeature
D/Camera  (19454): Updating builder with feature: ExposureOffsetFeature
D/Camera  (19454): Updating builder with feature: FpsRangeFeature
I/Camera  (19454): refreshPreviewCaptureSession
E/libEGL  (19454): call to OpenGL ES API with no current context (logged once per thread)
I/InterpreterApi(19454): Loaded native library: tensorflowlite_jni
I/InterpreterApi(19454): Didn't load native library: tensorflowlite_jni_gms_client
I/tflite  (19454): Initialized TensorFlow Lite runtime.
E/libc    (19454): Access denied finding property "ro.hardware.chipname"
I/tflite  (19454): Created TensorFlow Lite XNNPACK delegate for CPU.
I/tflite  (19454): Replacing 362 node(s) with delegate (TfLiteXNNPackDelegate) node, yielding 25 partitions.
D/FrameIndicator(19454): support status: 1 0x750059b018 0x750059b4c4
W/BpBinder(19454): Slow Binder: BpBinder transact took 564 ms, interface=android.hardware.camera2.ICameraDeviceUser, code=14 oneway=false
W/BpBinder(19454): Slow Binder: BpBinder transact took 281 ms, interface=android.hardware.camera2.ICameraDeviceUser, code=6 oneway=false
I/Camera  (19454): startPreviewWithImageStream
W/xample.new_pro(19454): Long monitor contention with owner main (19454) at void android.hardware.camera2.impl.CameraDeviceImpl.waitUntilIdle()(CameraDeviceImpl.java:1307) waiters=0 in void android.hardware.camera2.impl.CameraDeviceImpl$4.run() for 850ms
W/xample.new_pro(19454): Long monitor contention with owner main (19454) at void android.hardware.camera2.impl.CameraDeviceImpl.waitUntilIdle()(CameraDeviceImpl.java:1307) waiters=1 in void android.hardware.camera2.impl.CameraDeviceImpl$CameraDeviceCallbacks.onCaptureStarted(android.hardware.camera2.impl.CaptureResultExtras, long) for 736ms
I/Camera  (19454): CameraCaptureSession onConfigured
I/Camera  (19454): Updating builder settings
D/Camera  (19454): Updating builder with feature: ExposureLockFeature
D/Camera  (19454): Updating builder with feature: ExposurePointFeature
D/Camera  (19454): Updating builder with feature: ZoomLevelFeature
D/Camera  (19454): Updating builder with feature: AutoFocusFeature
D/Camera  (19454): Updating builder with feature: NoiseReductionFeature
I/Camera  (19454): updateNoiseReduction | currentSetting: fast
D/Camera  (19454): Updating builder with feature: FocusPointFeature
D/Camera  (19454): Updating builder with feature: ResolutionFeature
D/Camera  (19454): Updating builder with feature: SensorOrientationFeature
D/Camera  (19454): Updating builder with feature: FlashFeature
D/Camera  (19454): Updating builder with feature: ExposureOffsetFeature
D/Camera  (19454): Updating builder with feature: FpsRangeFeature
I/Camera  (19454): refreshPreviewCaptureSession
I/Camera  (19454): CameraCaptureSession onClosed
I/flutter (19454): Instance of 'CameraImage'
D/RenderScript HIDL Adaptation(19454): IRenderScriptDevice::getService()
W/System  (19454): A resource failed to call release. 
I/flutter (19454): Instance of 'CameraImage'
D/RenderScript HIDL Adaptation(19454): IRenderScriptDevice::getService() returned 0xb400007574e4b7a0
D/RenderScript HIDL Adaptation(19454): HIDL successfully loaded.
E/linker  (19454): library "" ("/apex/com.android.vndk.v30/lib64") needed or dlopened by "/apex/com.android.vndk.v30/lib64/libRS_internal.so" is not accessible for the namespace: [name="rs", ld_library_paths="", default_library_paths="/apex/com.android.vndk.v30/lib64:/vendor/lib64", permitted_paths="/odm/lib64:/vendor/lib64:/system/vendor/lib64:/data"]
E/RenderScript(19454): Failed loading RS driver: dlopen failed: library "" needed or dlopened by "/apex/com.android.vndk.v30/lib64/libRS_internal.so" is not accessible for the namespace "rs"
E/RenderScript(19454): Failed to load runtime , loading default
D/xample.new_pro(19454): Successfully queried cache dir: /data/user_de/0/com.example.new_proj/code_cache
D/RenderScript(19454): Setting cache dir: /data/user_de/0/com.example.new_proj/code_cache`
