### ISSUE TITLE
What is this "spa.traineddata" and "tessdata_config.json" files?

### ISSUE THREAD

**Issue by DholaSain** [vladiH/flutter_vision#2]
As I previsouly used tflite, where we don't use more then two files [ model.tflite, lable.txt ].
But in this pkg i don't know what to use in it... I'm getting emptry array from response.data.

**Comment by vladiH** [comment]
You need to train a yolov5 model following the documentation described in this repo [YoloV5][https://github.com/ultralytics/yolov5/wiki/Train-Custom-Data] and transform it to `.tflite` following the guideline described here [To tflite][https://github.com/ultralytics/yolov5/issues/251], `label.txt` is a `.txt` file which have all categories that your model can predict, example if your model was trained for predict cat and dog you must have putted this tags in this file line by line 
>cat
dog

**Comment by vladiH** [comment]
`spa.traineddata` and `tessdata_config.json` is used for OCR if you need to extract text from the detected region.
`spa.traineddata` is trained weight to get Spanish text from detected region. You can get different trained weight from here [dataset](https://github.com/tesseract-ocr/tessdata). Finally,  `tessdata_config.json` is only a reference file to put which language weight use on inference if you have more than one language.
`spa.traineddata` and `tessdata_config.json` is used for OCR if you need to extract text from the detected region.
`spa.traineddata` is trained weight to get Spanish text from detected region. You can get different trained weight from here [dataset](https://github.com/tesseract-ocr/tessdata). Finally,  `tessdata_config.json` is only a reference file to put which language weight use on inference if you have more than one language.

**Comment by vladiH** [comment]
In the next release, Yolov5, Tesseract and OCR model will be used separately from each other

**Comment by vladiH** [comment]
New version was launched
