### ISSUE TITLE
YOLO Results documentation in README

### ISSUE THREAD

**Issue by fransay** [vladiH/flutter_vision#24]
Hi @vladiH,
Kindly have a look at the coordinate representation of the box. 
`I think this should be the correct representation [x1:left, y1:top, x2:right, y2:bottom]`.
I don't know if this is right with respect to your package, but this is what I have found to work.
I hope you consider this request and make the possible changes needed.
Many thanks

```
   Map<String, dynamic>:{
    "box": [x1:top, y1:left, x2:bottom, y2:right, class_confidence]
    "tag": String: detected class
   }

```

**Comment by lorenzjedd** [comment]
hello, have you managed to make it work? I can't make It work on my end

**Comment by lorenzjedd** [comment]
I managed to make it work but only YoloVideo works.
YoloImage isn't doing anything on my end.

Also there's a bug on where YoloVideo wouldn't work after using YoloImage ( I pressed Detect on it )
