### ISSUE TITLE
Realtime object detection use camera plugin and best-fp16.tflite model

### ISSUE THREAD

**Issue by robinxcode** [vladiH/flutter_vision#3]
Hello, I'm currently trying to learn to use flutter_vision and the yolov5 model (best-fp16.tflite) that is in the example in this package and follow the steps and connect it to the camera. I've tried to point the camera at some of the objects listed in labels.txt (fingerprint/card), but the detection results give me null.

Is the way I connect yolov5 (best-fp16.tflite) with the camera wrong? or because the object that I pointed at the camera is not right? or maybe because of something else?

I don't have a yolov5 model, I'd like to learn how to build a model if it connects successfully.

![image](https://user-images.githubusercontent.com/69396159/174740453-e036545c-7225-476d-8924-a47761d2b94c.png)

![image](https://user-images.githubusercontent.com/69396159/174735188-520acdde-b672-4bc6-ba49-47a21174603a.png)

**Comment by vladiH** [comment]
I have tested it and work ok. Probably you have forgotten to add `assets/model/tes_yolov5/best-fp16.ftlite` and `assets/model/tes_yolov5/labels.txt` in `pubspect.yaml` as asset. Check documentation file.

<img width="190" alt="image" src="https://user-images.githubusercontent.com/32783435/174856752-1368c2f1-ae76-43c5-bb35-5f7cd71dafcc.png">

Also add this:
<img width="407" alt="image" src="https://user-images.githubusercontent.com/32783435/174856483-8b701595-52c4-4e19-9af1-c240430b3605.png">
