### ISSUE TITLE
Please help me with getting the right coordinates of some detected region on images

### ISSUE THREAD

**Issue by mahdi-madadi** [vladiH/flutter_vision#31]
I am sorry that I have asked for this several times, but I could not solve this issue. Bellow is the code which is taken from flutter_vision package example code, please help me to crop the image after detecting the region of interest with yolov8 model. 
`yoloOnImage() async {
`
` yoloResults.clear();`

   
    Uint8List byte = await imageFile!.readAsBytes();
    final image = await decodeImageFromList(byte);
    imageHeight = image.height;
    imageWidth = image.width;
    final result = await widget.vision.yoloOnImage(
        bytesList: byte,
        imageHeight: image.height,
        imageWidth: image.width,
        iouThreshold: 0.8,
        confThreshold: 0.4,
        classThreshold: 0.5);
    if (result.isNotEmpty) {
      setState(() {
        yoloResults = result;
      });
    }
  }
`

**Comment by vladiH** [comment]
Please, could you continue the discussion in thread #30? Creating multiple threads about the same issue can make it harder to keep track of the problem and provide effective assistance. Your cooperation is greatly appreciated. Thank you!
