### ISSUE TITLE
Please help me with cropping images

### ISSUE THREAD

**Issue by mahdi-madadi** [vladiH/flutter_vision#32]
Please update the bellow code to crop the detected region with yolov8 model, because right now it draws bounding box around the detected object, but I need only the detected region, and I want to display it on screen instead of the whole image.

`
List<Widget> displayBoxesAroundRecognizedObjects(Size screen) {
    if (yoloResults.isEmpty) return [];

    double factorX = screen.width / (imageWidth);
    double imgRatio = imageWidth / imageHeight;
    double newWidth = imageWidth * factorX;
    double newHeight = newWidth / imgRatio;
    double factorY = newHeight / (imageHeight);

    double pady = (screen.height - newHeight) / 2;

    Color colorPick = const Color.fromARGB(255, 50, 233, 30);
    return yoloResults.map((result) {
      return Positioned(
        left: result["box"][0] * factorX,
        top: result["box"][1] * factorY + pady,
        width: (result["box"][2] - result["box"][0]) * factorX,
        height: (result["box"][3] - result["box"][1]) * factorY,
        child: Container(
          decoration: BoxDecoration(
            borderRadius: const BorderRadius.all(Radius.circular(10.0)),
            border: Border.all(color: Colors.pink, width: 2.0),
          ),
          child: Text(
            "${result['tag']} ${(result['box'][4] * 100).toStringAsFixed(0)}%",
            style: TextStyle(
              background: Paint()..color = colorPick,
              color: Colors.white,
              fontSize: 18.0,
            ),
          ),
        ),
      );
    }).toList();
  }
}
`

**Comment by vladiH** [comment]
Please refrain from opening new issues related to the same questions. Everything related to this matter is discussed in issue #30. Thank you!

**Comment by mahdi-madadi** [comment]
I am sorry, but the issue is still persist
