### ISSUE TITLE
Make gray CameraImage before OCR recognition.

### ISSUE THREAD

**Issue by krammnic** [vladiH/flutter_vision#4]
As I know tesseract works better if image is grayscale. ocrOnFrame is accepting only CameraImage and I didn't find a way to make it gray

**Comment by vladiH** [comment]
CameraOnImage  does automatically this changes, don't care about it :)

**Comment by krammnic** [comment]
But is there any way to improve accuracy of tesseract recognition? You said that I don't need to do any image preprocessing, so what should I do to improve it?

**Comment by vladiH** [comment]
This is flow that flutter_vision do,  if you need more accuracy, you should modify preprocess phase, and it must be in `c++`, `c` or `golang` language, but it is not possible yet.

<img width="296" alt="image" src="https://user-images.githubusercontent.com/32783435/180472852-1b26d517-3a08-4a98-b87f-fe8c8def0632.png">

In the next release YoloV5, Tesseract and OCR will be apart each one to other, and you will have this possibility to modified intermediate phase with dart code assuming speed loss yourself
